# Imagem oficial do Tomcat baseada no Temurin (JDK)
FROM tomcat:10.1-jdk21-temurin

# Remove as aplicações padrão do Tomcat para manter o servidor limpo
#RUN rm -rf /usr/local/tomcat/webapps/*

# Copia o arquivo .war da sua aplicação para o diretório webapps do Tomcat
#COPY target/sua-aplicacao.war /usr/local/tomcat/webapps/ROOT.war

# Expõe a porta padrão do Tomcat
EXPOSE 8080

# Comando para iniciar o servidor
CMD ["catalina.sh", "run"]